// Outreach cadence sequencer (the sales team running itself) - MANUAL TRIGGER ONLY.
// Advances funnel leads through the touch cadence and sends each touch from eric@.
// STOPS the instant a lead engages / replies / books (handled elsewhere), checks
// suppression before every send, recycles Not-Now leads.
//
// DOUBLE-GATED so it can never fire by accident:
//   1) there is NO schedule - it only runs when you press "Run workflow" (or Claude triggers it)
//   2) it only actually sends when outreach_config.sending_enabled = true AND a real
//      physical_address is set. Otherwise it does a DRY preview (logs who it would send to).
//
// Optional slice inputs (env): SLICE_TIER (A|B|C), SLICE_SPECIALTY, SLICE_LIMIT.
// Env: SUPABASE_URL, SUPABASE_SERVICE_KEY, ERIC_USER, MDRX_ERIC_PASS
import nodemailer from 'nodemailer';
import { readFileSync } from 'fs';

const SITE = 'https://mdconcierge.net';
const ERIC_USER = process.env.ERIC_USER || 'eric@mdconcierge.net';
const ERIC_PASS = process.env.MDRX_ERIC_PASS || process.env.ERIC_APP_PASSWORD;
const { SUPABASE_URL, SUPABASE_SERVICE_KEY } = process.env;
for (const [k, v] of Object.entries({ ERIC_PASS, SUPABASE_URL, SUPABASE_SERVICE_KEY })) { if (!v) { console.error('Missing env: ' + k); process.exit(1); } }

const H = { apikey: SUPABASE_SERVICE_KEY, Authorization: 'Bearer ' + SUPABASE_SERVICE_KEY, 'Content-Type': 'application/json' };
const sGet = async (p) => { const r = await fetch(`${SUPABASE_URL}/rest/v1/${p}`, { headers: H }); return r.ok ? r.json() : []; };
const sPatch = async (p, row) => { const r = await fetch(`${SUPABASE_URL}/rest/v1/${p}`, { method: 'PATCH', headers: { ...H, Prefer: 'return=minimal' }, body: JSON.stringify(row) }); if (!r.ok) console.error(`patch ${p} ${r.status}: ${await r.text()}`); };
const today = () => new Date().toISOString().slice(0, 10);
const addDaysISO = (n) => new Date(Date.now() + n * 86400000).toISOString().slice(0, 10);
const addMonthsISO = (m) => { const d = new Date(); d.setMonth(d.getMonth() + m); return d.toISOString().slice(0, 10); };

const SUBJECTS = [
  "injured workers getting their meds, and the practice's side of it",
  "the 700 Pharmacy decision, in one page",
  "a cleaner way to handle your work-comp scripts",
];
const links = (t) => ({ overview: `${SITE}/go.html?p=${t}&to=brief`, book: `${SITE}/book.html?p=${t}`, unsub: `${SITE}/unsubscribe.html?p=${t}` });
const footer = (cfg, t) => { const l = links(t); return `\n\n${cfg.from_name}\n${cfg.physical_address}\nUnsubscribe: ${l.unsub}`; };

// Touch 1 = the approved designed email (HTML template + plain-text fallback).
const TOUCH1_HTML = readFileSync(new URL('./email-templates/touch1.html', import.meta.url), 'utf8');
const TOUCH1_SUBJECT = 'Big news for Pennsylvania practices that treat injured workers';
const mergeTouch1 = (p, cfg) => TOUCH1_HTML
  .replace(/\{\{last\}\}/g, p.last_name || '')
  .replace(/\{\{token\}\}/g, p.funnel_token || '')
  .replace(/\{\{address\}\}/g, cfg.physical_address || '');
function touch1Text(p, cfg) {
  const t = p.funnel_token;
  return `Dr. ${p.last_name || ''},\n\nIf you treat injured workers, the Pennsylvania Supreme Court recently expanded how physicians can participate in workers' compensation pharmacy. The decision creates a new opportunity to improve patient adherence while allowing your practice to share in the revenue generated by the prescriptions you're already writing.\n\nOn June 16, 2026, in 700 Pharmacy v. Bureau of Workers' Compensation Fee Review, the Court confirmed that physicians may have a financial interest in a workers' compensation pharmacy, and that insurers cannot deny payment for covered prescriptions on that basis.\n\nWhat this means for your practice:\n- Improve post-operative medication adherence with home delivery at no cost to injured workers while their claim is open.\n- Participate in the revenue generated by the workers' compensation prescriptions you're already writing instead of referring those prescriptions elsewhere.\n- Continue prescribing exactly as you do today. No workflow changes or additional administrative burden for you or your staff.\n\nThis isn't a new concept. Our workers' compensation mail-order pharmacy claims purchasing program lets your practice participate without owning or running a pharmacy. It has served physicians for more than a decade, and we handle the pharmacy operations, collections, compliance, customer service, and patient support so your team doesn't have to.\n\nResources:\n- Read the Pennsylvania Supreme Court decision: ${SITE}/go.html?p=${t}&to=decision\n- Daniel Siegel's practical takeaways for physicians: ${SITE}/go.html?p=${t}&to=siegel\n- Alice Gosfield's legal analysis: ${SITE}/go.html?p=${t}&to=gosfield\n- See how our program works: ${SITE}/go.html?p=${t}&to=program\n\nIf you think this could be valuable for your practice, I would be happy to show you how the program works and answer any compliance questions.\n\nSchedule a 15 minute call: ${SITE}/go.html?p=${t}&to=book\nOr simply reply to this email with any questions.\n\nBest,\nEric Weiscarger\nFounder | MDconcierge\n\nMDconcierge\n${cfg.physical_address}\nUnsubscribe: ${SITE}/unsubscribe.html?p=${t}`;
}
function body(touch, p, cfg) {
  const l = links(p.funnel_token); const first = p.first_name || 'there';
  if (touch === 1) return touch1Text(p, cfg);
  const dr = `Dr. ${p.last_name || ''}`.trim();
  if (touch === 2) return `${dr}, following up on my note about the Pennsylvania Supreme Court's 700 Pharmacy decision and what it means for practices that treat injured workers. No agenda. I think it is directly relevant to the work-comp prescriptions your practice already writes. The decision and a short overview of our program are here whenever you have a minute: ${l.overview}` + footer(cfg, p.funnel_token);
  if (touch === 3) return `${dr}, I will keep this short. If it is ever useful, the decision and our program overview answer most of the questions on their own: ${l.overview}. And if you would rather talk it through, my calendar is open: ${l.book}` + footer(cfg, p.funnel_token);
  return `${dr}, I will close the loop here so I am not crowding your inbox. If the timing is not right, no problem at all. If it is ever worth a look, the decision and program details are here: ${l.overview}, and my calendar is open if you would prefer to talk: ${l.book}. Either way, I wish you and your patients well.` + footer(cfg, p.funnel_token);
}

async function run() {
  const cfg = (await sGet('outreach_config?id=eq.1'))[0];
  if (!cfg) { console.log('no outreach_config'); return; }
  const addrOk = cfg.physical_address && !/SET PHYSICAL ADDRESS/i.test(cfg.physical_address);
  const DRY = !cfg.sending_enabled || !addrOk;
  const cad = cfg.cadence || { t1_day: 1, t2_day: 4, t3_day: 9, breakup_day: 16, recycle_months: 3 };
  console.log(`cadence ${today()} | mode=${DRY ? 'DRY PREVIEW (no send)' : 'LIVE'} | cap=${cfg.daily_send_cap}${addrOk ? '' : ' | reason: no real address'}${cfg.sending_enabled ? '' : ' | reason: sending_enabled off'}`);

  // Recycle Not-Now leads whose recycle_date arrived.
  const rec = await sGet(`mdrx_providers?select=id&lead_type=eq.funnel&funnel_stage=eq.Not%20Now&recycle_date=lte.${today()}`);
  for (const r of rec) await sPatch(`mdrx_providers?id=eq.${r.id}`, { funnel_stage: 'Queued', touch_count: 0, next_step: 'Touch 1', funnel_next_date: today(), recycle_date: null });
  if (rec.length) console.log(`recycled ${rec.length} Not-Now -> Queued`);

  // Optional slice filters for the manual trigger.
  let q = `mdrx_providers?select=id,first_name,last_name,practice_name,personalized_opener,funnel_token,email,touch_count&lead_type=eq.funnel&funnel_stage=in.(Queued,Contacted)&funnel_next_date=lte.${today()}&email=not.is.null&suppressed=eq.false&order=funnel_next_date.asc`;
  if (process.env.SLICE_TIER) q += `&intent_tier=eq.${encodeURIComponent(process.env.SLICE_TIER)}`;
  if (process.env.SLICE_SPECIALTY) q += `&target_specialty=eq.${encodeURIComponent(process.env.SLICE_SPECIALTY)}`;
  const cap = Number(process.env.SLICE_LIMIT) || cfg.daily_send_cap || 40;
  q += `&limit=${cap}`;
  const leads = await sGet(q);
  console.log(`${leads.length} lead(s) due (cap ${cap})`);

  const transport = DRY ? null : nodemailer.createTransport({ host: 'smtp.zoho.com', port: 465, secure: true, auth: { user: ERIC_USER, pass: ERIC_PASS } });
  let sent = 0, skipped = 0;
  for (const p of leads) {
    const sup = await sGet(`suppressions?select=email&email=ilike.${encodeURIComponent(p.email)}`);
    if (sup.length) { skipped++; continue; }
    const touch = (p.touch_count || 0) + 1;
    if (touch > 4) { await sPatch(`mdrx_providers?id=eq.${p.id}`, { funnel_stage: 'Not Now', next_step: 'Recycle', recycle_date: addMonthsISO(cad.recycle_months || 3), funnel_next_date: null }); continue; }
    const subject = touch === 1 ? TOUCH1_SUBJECT : SUBJECTS[(touch - 2) % SUBJECTS.length];
    const text = body(touch, p, cfg);
    const html = touch === 1 ? mergeTouch1(p, cfg) : undefined;
    if (DRY) { console.log(`[dry] touch ${touch} -> ${p.email} (${p.first_name} ${p.last_name})`); sent++; continue; }
    try { await transport.sendMail({ from: `"${cfg.from_name}" <${ERIC_USER}>`, to: p.email, subject, text, html }); }
    catch (e) { console.error(`send failed ${p.email}: ${e.message}`); skipped++; continue; }
    const nextDate = touch === 1 ? addDaysISO(cad.t2_day - cad.t1_day) : touch === 2 ? addDaysISO(cad.t3_day - cad.t2_day) : touch === 3 ? addDaysISO(cad.breakup_day - cad.t3_day) : null;
    const patch = { touch_count: touch, last_touch_at: new Date().toISOString(), funnel_stage: 'Contacted', next_step: `Touch ${touch + 1}`, funnel_next_date: nextDate };
    if (touch === 4) { patch.funnel_stage = 'Not Now'; patch.next_step = 'Recycle'; patch.recycle_date = addMonthsISO(cad.recycle_months || 3); patch.funnel_next_date = patch.recycle_date; }
    await sPatch(`mdrx_providers?id=eq.${p.id}`, patch);
    sent++;
  }
  console.log(`done. ${DRY ? 'would-send' : 'SENT'}=${sent} skipped=${skipped}`);
}
run().catch(e => { console.error('Fatal: ' + (e?.stack || e)); process.exit(1); });
