// Outreach queue builder (behavior-aware). Populates mdrx_outbox with the day's
// due touches for Eric to APPROVE and send (via the send-outreach edge function).
// It SENDS NOTHING itself. The sequence is behavior-driven, not a dumb timer:
//   - It only queues leads in Queued/New/Contacted whose next touch is due.
//   - Leads who replied, engaged, opted out, or booked are Engaged/Replied/
//     Not Interested/Unsubscribed/Won and are EXCLUDED here (handled by the reply
//     agent + next-move agent). That is the automatic stop.
//   - Suppressed and no-email leads are skipped. Warm-up ramp + per-practice pacing.
// Env: SUPABASE_URL, SUPABASE_SERVICE_KEY.
const { SUPABASE_URL, SUPABASE_SERVICE_KEY } = process.env;
for (const [k, v] of Object.entries({ SUPABASE_URL, SUPABASE_SERVICE_KEY })) { if (!v) { console.error('Missing env: ' + k); process.exit(1); } }

import { readFileSync } from 'node:fs';

const SITE = 'https://mdconcierge.net';

// Touch 1 = the approved DESIGNED email. body_text below stays as the plain-text
// alternative; send-outreach sends body_html when present and falls back to text.
const TOUCH1_HTML = readFileSync(new URL('./email-templates/touch1.html', import.meta.url), 'utf8');
// Eric's signature lives INSIDE the card, not appended after it. send-outreach sees the
// <!--signature-inline--> marker and skips its own append so it never doubles up.
const SIGNATURE_HTML = readFileSync(new URL('./email-templates/signature.html', import.meta.url), 'utf8');
// No per-lead opener line. A generic specialty statement reads as filler to a physician
// who already knows it, so Touch 1 opens on the news itself.
const mergeTouch1 = (p) => {
  return TOUCH1_HTML
    .replace(/\{\{signature\}\}/g, SIGNATURE_HTML)
    .replace(/\{\{last\}\}/g, p.last_name || '')
    .replace(/\{\{token\}\}/g, p.funnel_token || '');
};
const H = { apikey: SUPABASE_SERVICE_KEY, Authorization: 'Bearer ' + SUPABASE_SERVICE_KEY, 'Content-Type': 'application/json' };
const sGet = async (p) => { const r = await fetch(`${SUPABASE_URL}/rest/v1/${p}`, { headers: H }); return r.ok ? r.json() : []; };
const sPost = async (t, row) => { const r = await fetch(`${SUPABASE_URL}/rest/v1/${t}`, { method: 'POST', headers: { ...H, Prefer: 'return=minimal' }, body: JSON.stringify(row) }); if (!r.ok) console.error(`insert ${t} ${r.status}: ${await r.text()}`); };
const sPatch = async (p, row) => { const r = await fetch(`${SUPABASE_URL}/rest/v1/${p}`, { method: 'PATCH', headers: { ...H, Prefer: 'return=minimal' }, body: JSON.stringify(row) }); if (!r.ok) console.error(`patch ${p} ${r.status}: ${await r.text()}`); };
const today = () => new Date().toISOString().slice(0, 10);
const addDaysISO = (n) => new Date(Date.now() + n * 86400000).toISOString().slice(0, 10);

// Clean, personal plain-text touches. No address, no unsubscribe. End at "Best,"
// (the signature is attached at send time by the send-outreach function).
const link = (t, to) => `${SITE}/go.html?p=${t}&to=${to}`;
function touchBody(touch, p) {
  const dr = `Dr. ${p.last_name || ''}`.trim();
  const t = p.funnel_token || '';
  if (touch === 1) {
    // Plain-text alternative. Must mirror email-templates/touch1.html: the ruling material is
    // sourced to the opinion and to Siegel's takeaways; the program claims stay separate.
    return `${dr},\n\nOn June 16, 2026, the Pennsylvania Supreme Court ruled that Pennsylvania's workers' compensation anti-referral law does not apply to prescription drugs. The Court's stated concern was continuity of care, so that injured workers keep receiving medication from a pharmacy that knows their history and treatment plan rather than having that care interrupted. A physician may now refer workers' compensation prescriptions to a pharmacy in which they hold a financial interest, and an insurer cannot refuse to pay because of that interest. The case is 700 Pharmacy v. Bureau of Workers' Compensation Fee Review Hearing Office. If you care for injured workers, it affects how their prescriptions can be handled.\n\nFor years, the revenue generated by workers' compensation prescriptions has gone to parties with no role in treating the patient. The physician actually caring for the injured worker was the one party who could not participate. That is what this decision changes.\n\nDaniel Siegel, who argued the case before the Court, summarized the practical takeaways this way:\n\n- For physicians. They can refer patients to a pharmacy they own or have a financial interest in for prescription drugs, supporting continuity of care.\n- For pharmacies. Pharmacies owned by physicians can seek payment for prescriptions provided to workers' compensation claimants, even if the referring doctor has a financial interest.\n- For insurers. Insurers cannot deny payment for prescription drugs on the grounds of prohibited self-referral under the current law.\n\nIf you'd like to review the legal foundation before we speak, I've included several resources below:\n- Pennsylvania Supreme Court decision: ${link(t, 'decision')}\n- Daniel Siegel's practical analysis for Pennsylvania physicians: ${link(t, 'siegel')}\n- Alice Gosfield's legal analysis: ${link(t, 'gosfield')}\n- Overview of our Workers' Compensation Pharmacy Platform: ${link(t, 'program')}\n\nWe operate a Workers' Compensation Pharmacy Platform for individual physicians or practices that want to participate. For those that do, it means better access to medication for the injured worker, less administrative burden on your staff, and meaningful revenue from the workers' compensation prescriptions you are already writing.\n\nMore about our program: ${link(t, 'program')}\nBook a call: ${link(t, 'book')}\n\nOr simply reply to this email with any questions.\n\nBest,`;
  }
  if (touch === 2) return `${dr},\n\nFollowing up on my note about the Pennsylvania Supreme Court's 700 Pharmacy decision and what it means for practices that treat injured workers. I think it is directly relevant to the work-comp scripts your practice already writes. The decision and a short overview are here whenever you have a minute: ${link(t, 'program')}\n\nBest,`;
  if (touch === 3) return `${dr},\n\nKeeping this short. If it is useful, the decision and our program overview answer most questions on their own: ${link(t, 'program')}. And if you would rather talk it through, my calendar is open: ${link(t, 'book')}\n\nBest,`;
  return `${dr},\n\nI will close the loop here so I am not crowding your inbox. If the timing is not right, no problem at all. If it is ever worth a look, the decision and program details are here: ${link(t, 'program')}, and my calendar is open if you would prefer to talk: ${link(t, 'book')}. Either way, I wish you and your patients well.\n\nBest,`;
}
const SUBJECTS = {
  1: "Pennsylvania Supreme Court Confirms Physicians May Have a Financial Interest in Workers' Compensation Pharmacy",
  2: "Following up: the 700 Pharmacy decision and your work-comp scripts",
  3: "A cleaner way to handle your work-comp pharmacy",
  4: "Closing the loop",
};

async function run() {
  const cfg = (await sGet('outreach_config?id=eq.1'))[0] || {};
  if (!cfg.warmup_started_at) await sPatch('outreach_config?id=eq.1', { warmup_started_at: today() });
  // Batch size: explicit BATCH_SIZE override (manual first batch), else the daily cap. Eric self-throttles by approving fewer.
  const cap = Number(process.env.BATCH_SIZE) || Number(cfg.daily_send_cap) || 20;

  // Recycle Not-Now leads whose recycle date arrived.
  const rec = await sGet(`mdrx_providers?select=id,recycle_round&lead_type=eq.funnel&funnel_stage=eq.Not%20Now&recycle_date=lte.${today()}`);
  for (const r of rec) await sPatch(`mdrx_providers?id=eq.${r.id}`, { funnel_stage: 'Queued', touch_count: 0, next_step: 'Touch 1', funnel_next_date: today(), recycle_date: null, recycle_round: (r.recycle_round || 0) + 1 });

  // Already-queued leads (avoid duplicates).
  const openBox = await sGet('mdrx_outbox?select=provider_id&status=eq.pending');
  const queued = new Set((openBox || []).map((x) => x.provider_id));
  const supp = await sGet('suppressions?select=email');
  const suppressed = new Set((supp || []).map((s) => (s.email || '').toLowerCase()));

  // Behavior-aware pool: only Queued/New/Contacted (NOT Engaged/Replied/Not Interested/Unsubscribed/Won/Lost),
  // due today, with an email, not suppressed. Hottest-first is not needed; go by due date.
  const pool = await sGet(`mdrx_providers?select=id,first_name,last_name,practice_name,funnel_token,email,touch_count,funnel_next_date,recycle_round,personalized_opener&lead_type=eq.funnel&funnel_stage=in.(New,Queued,Contacted)&email=not.is.null&suppressed=eq.false&or=(funnel_next_date.is.null,funnel_next_date.lte.${today()})&order=funnel_next_date.asc.nullsfirst&limit=400`);

  // Approved news openers, for A/B-rotating a fresh angle into recycled leads' first touch.
  const openers = await sGet(`mdrx_content_queue?select=id,draft_hook&status=eq.approved&kind=eq.opener&order=id.desc`);
  let openerIdx = 0;
  let queuedCount = 0; const practicesToday = new Set();
  for (const p of pool) {
    if (queuedCount >= cap) break;
    if (queued.has(p.id)) continue;
    if (suppressed.has((p.email || '').toLowerCase())) continue;
    const prac = (p.practice_name || '').toLowerCase();
    if (prac && practicesToday.has(prac)) continue; // pace by practice: max one per office per run
    const touch = (p.touch_count || 0) + 1;
    if (touch > 4) { await sPatch(`mdrx_providers?id=eq.${p.id}`, { funnel_stage: 'Not Now', next_step: 'Recycle', recycle_date: addDaysISO(90), funnel_next_date: addDaysISO(90) }); continue; }
    // A/B: a recycled lead's first touch leads with a fresh, approved news opener instead of repeating Touch 1.
    let bodyText = touchBody(touch, p), contentId = null;
    if (touch === 1 && (p.recycle_round || 0) > 0 && openers.length) {
      const op = openers[openerIdx % openers.length]; openerIdx++;
      if (op && op.draft_hook) {
        const dr = `Dr. ${p.last_name || ''}`.trim();
        bodyText = `${dr},\n\n${op.draft_hook}\n\nIf it is worth a look, my calendar is open: ${link(p.funnel_token || '', 'book')}, or just reply with any questions.\n\nBest,`;
        contentId = op.id;
      }
    }
    await sPost('mdrx_outbox', {
      provider_id: p.id, touch_no: touch, to_email: p.email,
      subject: SUBJECTS[touch] || SUBJECTS[4], body_text: bodyText,
      body_html: touch === 1 && !contentId ? mergeTouch1(p) : null,
      status: 'pending', scheduled_date: today(), content_id: contentId,
    });
    if (contentId) { const cur = await sGet(`mdrx_content_queue?select=used_count&id=eq.${contentId}`); await sPatch(`mdrx_content_queue?id=eq.${contentId}`, { used_count: ((cur[0] && cur[0].used_count) || 0) + 1 }); }
    if (prac) practicesToday.add(prac);
    queued.add(p.id); queuedCount++;
  }
  console.log(`queue builder ${today()}: warmup day ${daysIn} cap ${cap}, queued ${queuedCount} touch(es) for approval. Recycled ${rec.length}.`);
}
run().catch((e) => { console.error('Fatal: ' + (e?.stack || e)); process.exit(1); });
