-- desk_items — the keeper's open items. One row per thing that is owed on a lead.
--
-- kind:
--   promise      Eric said he would do something in his own sent mail and it has not gone out
--   quiet        an engaged or later lead with no activity for 7 or more days
--   no_next_step a lead that had no next step or no date, and was given one
--   reply_waiting someone wrote in and has had no answer
--
-- dedupe_key carries the identity of the thing itself (lead, kind, and the message or date it came
-- from) so the same promise is never added twice. A quiet lead that comes back and goes quiet again
-- gets a new key, because the date it last moved is part of the key.
create table if not exists public.desk_items (
  id           bigint generated by default as identity primary key,
  provider_id  bigint references public.mdrx_providers(id) on delete cascade,
  kind         text not null check (kind in ('promise','quiet','no_next_step','reply_waiting')),
  title        text not null,
  detail       text,
  due_date     date,
  source       text,
  dedupe_key   text not null,
  status       text not null default 'open' check (status in ('open','done','dismissed')),
  created_at   timestamptz not null default now(),
  resolved_at  timestamptz
);

create unique index if not exists desk_items_dedupe_key_idx on public.desk_items (dedupe_key);
create index if not exists desk_items_open_idx on public.desk_items (status, kind, due_date);
create index if not exists desk_items_provider_idx on public.desk_items (provider_id);

-- Same posture as every other MDRx table: authenticated only, anon sees nothing.
alter table public.desk_items enable row level security;
drop policy if exists auth_all_desk_items on public.desk_items;
create policy auth_all_desk_items on public.desk_items
  for all to authenticated using (true) with check (true);
revoke all on public.desk_items from anon;
grant select, insert, update, delete on public.desk_items to authenticated;
